/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedConnectDomainRouteImport } from './routes/_authenticated/connect-domain'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedWebsiteRouteImport } from './routes/_authenticated/website'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicWhopWebhookRouteImport } from './routes/api/public/whop-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectDomainRoute =
  AuthenticatedConnectDomainRouteImport.update({
    id: '/connect-domain',
    path: '/connect-domain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteRoute = AuthenticatedWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhopWebhookRoute = ApiPublicWhopWebhookRouteImport.update({
  id: '/api/public/whop-webhook',
  path: '/api/public/whop-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/connect-domain': typeof AuthenticatedConnectDomainRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/connect-domain': typeof AuthenticatedConnectDomainRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/connect-domain': typeof AuthenticatedConnectDomainRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/website': typeof AuthenticatedWebsiteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/whop-webhook': typeof ApiPublicWhopWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/business'
    | '/connect-domain'
    | '/dashboard'
    | '/domains'
    | '/leads'
    | '/media'
    | '/onboarding'
    | '/seo'
    | '/settings'
    | '/support'
    | '/website'
    | '/auth/callback'
    | '/s/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/whop-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/business'
    | '/connect-domain'
    | '/dashboard'
    | '/domains'
    | '/leads'
    | '/media'
    | '/onboarding'
    | '/seo'
    | '/settings'
    | '/support'
    | '/website'
    | '/auth/callback'
    | '/s/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/whop-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/business'
    | '/_authenticated/connect-domain'
    | '/_authenticated/dashboard'
    | '/_authenticated/domains'
    | '/_authenticated/leads'
    | '/_authenticated/media'
    | '/_authenticated/onboarding'
    | '/_authenticated/seo'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/website'
    | '/auth/callback'
    | '/s/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/whop-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicWhopWebhookRoute: typeof ApiPublicWhopWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect-domain': {
      id: '/_authenticated/connect-domain'
      path: '/connect-domain'
      fullPath: '/connect-domain'
      preLoaderRoute: typeof AuthenticatedConnectDomainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website': {
      id: '/_authenticated/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AuthenticatedWebsiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whop-webhook': {
      id: '/api/public/whop-webhook'
      path: '/api/public/whop-webhook'
      fullPath: '/api/public/whop-webhook'
      preLoaderRoute: typeof ApiPublicWhopWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedConnectDomainRoute: typeof AuthenticatedConnectDomainRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWebsiteRoute: typeof AuthenticatedWebsiteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedConnectDomainRoute: AuthenticatedConnectDomainRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWebsiteRoute: AuthenticatedWebsiteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicWhopWebhookRoute: ApiPublicWhopWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
