-- Publish the expanded local-business template catalog.
INSERT INTO public.templates (slug, name, niche, description, status, current_version)
VALUES
  ('pressure-washing-01', 'Pressure Washing — Local Standard', 'pressure_washing', 'A polished, conversion-focused pressure washing website with original service photography and a clear enquiry journey.', 'published', 1),
  ('hvac-01', 'HVAC — Local Standard', 'hvac', 'A polished, conversion-focused hvac website with original service photography and a clear enquiry journey.', 'published', 1),
  ('electrical-contractor-01', 'Electrical Contractor — Local Standard', 'electrical_contractor', 'A polished, conversion-focused electrical contractor website with original service photography and a clear enquiry journey.', 'published', 1),
  ('painting-contractor-01', 'Painting Contractor — Local Standard', 'painting_contractor', 'A polished, conversion-focused painting contractor website with original service photography and a clear enquiry journey.', 'published', 1),
  ('handyman-01', 'Handyman — Local Standard', 'handyman', 'A polished, conversion-focused handyman website with original service photography and a clear enquiry journey.', 'published', 1),
  ('pest-control-01', 'Pest Control — Local Standard', 'pest_control', 'A polished, conversion-focused pest control website with original service photography and a clear enquiry journey.', 'published', 1),
  ('tree-service-01', 'Tree Service — Local Standard', 'tree_service', 'A polished, conversion-focused tree service website with original service photography and a clear enquiry journey.', 'published', 1),
  ('lawn-care-01', 'Lawn Care — Local Standard', 'lawn_care', 'A polished, conversion-focused lawn care website with original service photography and a clear enquiry journey.', 'published', 1),
  ('pool-service-01', 'Pool Service — Local Standard', 'pool_service', 'A polished, conversion-focused pool service website with original service photography and a clear enquiry journey.', 'published', 1),
  ('concrete-contractor-01', 'Concrete Contractor — Local Standard', 'concrete_contractor', 'A polished, conversion-focused concrete contractor website with original service photography and a clear enquiry journey.', 'published', 1),
  ('flooring-contractor-01', 'Flooring Contractor — Local Standard', 'flooring_contractor', 'A polished, conversion-focused flooring contractor website with original service photography and a clear enquiry journey.', 'published', 1),
  ('window-installation-01', 'Window Installation — Local Standard', 'window_installation', 'A polished, conversion-focused window installation website with original service photography and a clear enquiry journey.', 'published', 1),
  ('garage-door-service-01', 'Garage Door Service — Local Standard', 'garage_door_service', 'A polished, conversion-focused garage door service website with original service photography and a clear enquiry journey.', 'published', 1),
  ('home-inspection-01', 'Home Inspection — Local Standard', 'home_inspection', 'A polished, conversion-focused home inspection website with original service photography and a clear enquiry journey.', 'published', 1),
  ('water-damage-restoration-01', 'Water Damage Restoration — Local Standard', 'water_damage_restoration', 'A polished, conversion-focused water damage restoration website with original service photography and a clear enquiry journey.', 'published', 1),
  ('fire-damage-restoration-01', 'Fire Damage Restoration — Local Standard', 'fire_damage_restoration', 'A polished, conversion-focused fire damage restoration website with original service photography and a clear enquiry journey.', 'published', 1),
  ('bathroom-remodeling-01', 'Bathroom Remodeling — Local Standard', 'bathroom_remodeling', 'A polished, conversion-focused bathroom remodeling website with original service photography and a clear enquiry journey.', 'published', 1),
  ('kitchen-remodeling-01', 'Kitchen Remodeling — Local Standard', 'kitchen_remodeling', 'A polished, conversion-focused kitchen remodeling website with original service photography and a clear enquiry journey.', 'published', 1),
  ('window-cleaning-01', 'Window Cleaning — Local Standard', 'window_cleaning', 'A polished, conversion-focused window cleaning website with original service photography and a clear enquiry journey.', 'published', 1),
  ('masonry-contractor-01', 'Masonry Contractor — Local Standard', 'masonry_contractor', 'A polished, conversion-focused masonry contractor website with original service photography and a clear enquiry journey.', 'published', 1),
  ('auto-detailing-01', 'Auto Detailing — Local Standard', 'auto_detailing', 'A polished, conversion-focused auto detailing website with original service photography and a clear enquiry journey.', 'published', 1),
  ('auto-repair-01', 'Auto Repair — Local Standard', 'auto_repair', 'A polished, conversion-focused auto repair website with original service photography and a clear enquiry journey.', 'published', 1),
  ('tire-shop-01', 'Tire Shop — Local Standard', 'tire_shop', 'A polished, conversion-focused tire shop website with original service photography and a clear enquiry journey.', 'published', 1),
  ('locksmith-01', 'Locksmith — Local Standard', 'locksmith', 'A polished, conversion-focused locksmith website with original service photography and a clear enquiry journey.', 'published', 1),
  ('mobile-mechanic-01', 'Mobile Mechanic — Local Standard', 'mobile_mechanic', 'A polished, conversion-focused mobile mechanic website with original service photography and a clear enquiry journey.', 'published', 1),
  ('car-wash-01', 'Car Wash — Local Standard', 'car_wash', 'A polished, conversion-focused car wash website with original service photography and a clear enquiry journey.', 'published', 1),
  ('window-tinting-01', 'Window Tinting — Local Standard', 'window_tinting', 'A polished, conversion-focused window tinting website with original service photography and a clear enquiry journey.', 'published', 1),
  ('towing-service-01', 'Towing Service — Local Standard', 'towing_service', 'A polished, conversion-focused towing service website with original service photography and a clear enquiry journey.', 'published', 1),
  ('auto-battery-service-01', 'Auto Battery Service — Local Standard', 'auto_battery_service', 'A polished, conversion-focused auto battery service website with original service photography and a clear enquiry journey.', 'published', 1),
  ('car-rental-01', 'Car Rental — Local Standard', 'car_rental', 'A polished, conversion-focused car rental website with original service photography and a clear enquiry journey.', 'published', 1),
  ('barbershop-01', 'Barbershop — Local Standard', 'barbershop', 'A polished, conversion-focused barbershop website with original service photography and a clear enquiry journey.', 'published', 1),
  ('hair-salon-01', 'Hair Salon — Local Standard', 'hair_salon', 'A polished, conversion-focused hair salon website with original service photography and a clear enquiry journey.', 'published', 1),
  ('nail-salon-01', 'Nail Salon — Local Standard', 'nail_salon', 'A polished, conversion-focused nail salon website with original service photography and a clear enquiry journey.', 'published', 1),
  ('spa-01', 'Spa — Local Standard', 'spa', 'A polished, conversion-focused spa website with original service photography and a clear enquiry journey.', 'published', 1),
  ('massage-therapy-01', 'Massage Therapy — Local Standard', 'massage_therapy', 'A polished, conversion-focused massage therapy website with original service photography and a clear enquiry journey.', 'published', 1),
  ('gym-01', 'Gym — Local Standard', 'gym', 'A polished, conversion-focused gym website with original service photography and a clear enquiry journey.', 'published', 1),
  ('yoga-studio-01', 'Yoga Studio — Local Standard', 'yoga_studio', 'A polished, conversion-focused yoga studio website with original service photography and a clear enquiry journey.', 'published', 1),
  ('personal-trainer-01', 'Personal Trainer — Local Standard', 'personal_trainer', 'A polished, conversion-focused personal trainer website with original service photography and a clear enquiry journey.', 'published', 1),
  ('pet-grooming-01', 'Pet Grooming — Local Standard', 'pet_grooming', 'A polished, conversion-focused pet grooming website with original service photography and a clear enquiry journey.', 'published', 1),
  ('dog-training-01', 'Dog Training — Local Standard', 'dog_training', 'A polished, conversion-focused dog training website with original service photography and a clear enquiry journey.', 'published', 1),
  ('photography-01', 'Photography — Local Standard', 'photography', 'A polished, conversion-focused photography website with original service photography and a clear enquiry journey.', 'published', 1),
  ('wedding-services-01', 'Wedding Services — Local Standard', 'wedding_services', 'A polished, conversion-focused wedding services website with original service photography and a clear enquiry journey.', 'published', 1),
  ('moving-company-01', 'Moving Company — Local Standard', 'moving_company', 'A polished, conversion-focused moving company website with original service photography and a clear enquiry journey.', 'published', 1),
  ('storage-company-01', 'Storage Company — Local Standard', 'storage_company', 'A polished, conversion-focused storage company website with original service photography and a clear enquiry journey.', 'published', 1),
  ('real-estate-agent-01', 'Real Estate Agent — Local Standard', 'real_estate_agent', 'A polished, conversion-focused real estate agent website with original service photography and a clear enquiry journey.', 'published', 1),
  ('law-firm-01', 'Law Firm — Local Standard', 'law_firm', 'A polished, conversion-focused law firm website with original service photography and a clear enquiry journey.', 'published', 1),
  ('accountant-01', 'Accountant — Local Standard', 'accountant', 'A polished, conversion-focused accountant website with original service photography and a clear enquiry journey.', 'published', 1),
  ('insurance-agency-01', 'Insurance Agency — Local Standard', 'insurance_agency', 'A polished, conversion-focused insurance agency website with original service photography and a clear enquiry journey.', 'published', 1),
  ('dentist-01', 'Dentist — Local Standard', 'dentist', 'A polished, conversion-focused dentist website with original service photography and a clear enquiry journey.', 'published', 1),
  ('chiropractor-01', 'Chiropractor — Local Standard', 'chiropractor', 'A polished, conversion-focused chiropractor website with original service photography and a clear enquiry journey.', 'published', 1)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    niche = EXCLUDED.niche,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    current_version = EXCLUDED.current_version;
